---
fixtures:
  repositories:
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    simp_docker: https://github.com/simp/pupmod-simp-simp_docker
    # integration deps
    iptables: https://github.com/simp/pupmod-simp-iptables
    translate: https://github.com/simp/puppetlabs-translate
    ## deps for simp_docker
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_sysctl: https://github.com/simp/augeasproviders_sysctl
    docker:
      repo: https://github.com/simp/puppetlabs-docker
      ref: 1.0.5
