---
fixtures:
  repositories:
    # base deps
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      ref: 3.3.1
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      ref: 4.24.0
    # integration deps
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: master
    simp_docker:
      repo: https://github.com/simp/pupmod-simp-simp_docker
      branch: master
    ## deps for simp_docker
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      ref: 2.1.4
    augeasproviders_sysctl:
      repo: https://github.com/simp/augeasproviders_sysctl
      ref: 2.2.0
    docker:
      repo: https://github.com/simp/puppetlabs-docker
      # requires fixes to the upstream module that have not been released yet
      ref: 587748b6a5b140801f39cb883a1d92a4d40c662f
