HOSTS:
  master01:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_cpus: 2
    vagrant_memsize: 2024
    # forwarded_ports:
    #   nodeport:
    #     from: 8080
    #     to: 80
    #     from_ip: '127.0.0.1'
    #     to_ip: '0.0.0.0'
  # master02:
  #   roles:
  #     - kube-master
  #   platform:   el-7-x86_64
  #   box:        centos/7
  #   hypervisor: vagrant
  # master03:
  #   roles:
  #     - kube-master
  #   platform:   el-7-x86_64
  #   box:        centos/7
  #   hypervisor: vagrant
  worker01:
    roles:
      - worker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  worker02:
    roles:
      - worker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  worker03:
    roles:
      - worker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  synced_folder: disabled
  vagrant_memsize: 1024
# vb_gui: true
