HOSTS:
  master01:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  # master02:
  #   roles:
  #     - kube-master
  #   platform:   el-7-x86_64
  #   box:        centos/7
  #   hypervisor: vagrant
  # master03:
  #   roles:
  #     - kube-master
  #   platform:   el-7-x86_64
  #   box:        centos/7
  #   hypervisor: vagrant
  worker01:
    roles:
      - worker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  worker02:
    roles:
      - worker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  worker03:
    roles:
      - worker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 512
  synced_folder: disabled
# vb_gui: true
